[package]
name = "comp-rs"
version = "0.1.0"
authors = ["Gustavo Murayama <gmurayama@outlook.com>", "Lucas Tornai <lucastornai00@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"